services:
  web:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - .:/app
      - ./data:/data
      - ./sessions:/sessions
    env_file:
      - .env
    command: >
      sh -c "
        echo \"ENV PORT: $${PORT}\" &&
        python init_db.py &&
        EXTERNAL_PORT=$${PORT:-8000} &&
        echo \"Starting Uvicorn on internal port 8000 (mapped to external port $${EXTERNAL_PORT})\" &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

# Named volumes
volumes:
  data:
  sessions: