version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/data
    environment:
      - DATABASE_URL=sqlite:////data/my_relations_app.db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  data: