"""Add leeft field to Personen

Revision ID: 415c032003d7
Revises: b934cd664baf
Create Date: 2024-07-20 17:45:40.168228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '415c032003d7'
down_revision: Union[str, None] = 'b934cd664baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('personen', sa.Column('leeft', sa.Boolean(), nullable=False))
    op.add_column('personen', sa.Column('leeft', sa.Boolean(), nullable=True))
    op.execute("UPDATE personen SET leeft = True WHERE leeft IS NULL")
    with op.batch_alter_table('personen') as batch_op:
        batch_op.alter_column('leeft', nullable=False, server_default=sa.true())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personen') as batch_op:
        batch_op.drop_column('leeft')
    # ### end Alembic commands ###
