"""Initial migration

Revision ID: b934cd664baf
Revises: 
Create Date: 2024-07-20 14:51:49.416483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b934cd664baf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('familienaam', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('straatnaam', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('huisnummer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('huisnummer_toevoeging', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plaats', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jubileumtypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jubileumtypes_naam'), 'jubileumtypes', ['naam'], unique=True)
    op.create_table('relatietypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relatienaam', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rollen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rollen_naam'), 'rollen', ['naam'], unique=True)
    op.create_table('gebruikers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('naam', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('google_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rollen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gebruikers_email'), 'gebruikers', ['email'], unique=True)
    op.create_index(op.f('ix_gebruikers_google_id'), 'gebruikers', ['google_id'], unique=True)
    op.create_table('personen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voornaam', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('achternaam', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('familie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['familie_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jubilea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jubileumdag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('omschrijving', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('persoon_id', sa.Integer(), nullable=True),
    sa.Column('jubileumtype_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jubileumtype_id'], ['jubileumtypes.id'], ),
    sa.ForeignKeyConstraint(['persoon_id'], ['personen.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relaties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persoon1_id', sa.Integer(), nullable=False),
    sa.Column('persoon2_id', sa.Integer(), nullable=False),
    sa.Column('relatietype_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persoon1_id'], ['personen.id'], ),
    sa.ForeignKeyConstraint(['persoon2_id'], ['personen.id'], ),
    sa.ForeignKeyConstraint(['relatietype_id'], ['relatietypes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relaties')
    op.drop_table('jubilea')
    op.drop_table('personen')
    op.drop_index(op.f('ix_gebruikers_google_id'), table_name='gebruikers')
    op.drop_index(op.f('ix_gebruikers_email'), table_name='gebruikers')
    op.drop_table('gebruikers')
    op.drop_index(op.f('ix_rollen_naam'), table_name='rollen')
    op.drop_table('rollen')
    op.drop_table('relatietypes')
    op.drop_index(op.f('ix_jubileumtypes_naam'), table_name='jubileumtypes')
    op.drop_table('jubileumtypes')
    op.drop_table('families')
    # ### end Alembic commands ###
